; Auto-generated. Do not edit!


(cl:in-package actionlib_tut-msg)


;//! \htmlinclude moveFeedback.msg.html

(cl:defclass <moveFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback_num
    :reader feedback_num
    :initarg :feedback_num
    :type cl:integer
    :initform 0))
)

(cl:defclass moveFeedback (<moveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tut-msg:<moveFeedback> is deprecated: use actionlib_tut-msg:moveFeedback instead.")))

(cl:ensure-generic-function 'feedback_num-val :lambda-list '(m))
(cl:defmethod feedback_num-val ((m <moveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tut-msg:feedback_num-val is deprecated.  Use actionlib_tut-msg:feedback_num instead.")
  (feedback_num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveFeedback>) ostream)
  "Serializes a message object of type '<moveFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'feedback_num)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveFeedback>) istream)
  "Deserializes a message object of type '<moveFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback_num) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveFeedback>)))
  "Returns string type for a message object of type '<moveFeedback>"
  "actionlib_tut/moveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveFeedback)))
  "Returns string type for a message object of type 'moveFeedback"
  "actionlib_tut/moveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveFeedback>)))
  "Returns md5sum for a message object of type '<moveFeedback>"
  "0ef00485d510719cdd8130a85bb4b231")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveFeedback)))
  "Returns md5sum for a message object of type 'moveFeedback"
  "0ef00485d510719cdd8130a85bb4b231")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveFeedback>)))
  "Returns full string definition for message of type '<moveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 feedback_num~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveFeedback)))
  "Returns full string definition for message of type 'moveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 feedback_num~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'moveFeedback
    (cl:cons ':feedback_num (feedback_num msg))
))
