; Auto-generated. Do not edit!


(cl:in-package actionlib_tut-msg)


;//! \htmlinclude moveResult.msg.html

(cl:defclass <moveResult> (roslisp-msg-protocol:ros-message)
  ((res_num
    :reader res_num
    :initarg :res_num
    :type cl:integer
    :initform 0))
)

(cl:defclass moveResult (<moveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tut-msg:<moveResult> is deprecated: use actionlib_tut-msg:moveResult instead.")))

(cl:ensure-generic-function 'res_num-val :lambda-list '(m))
(cl:defmethod res_num-val ((m <moveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tut-msg:res_num-val is deprecated.  Use actionlib_tut-msg:res_num instead.")
  (res_num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveResult>) ostream)
  "Serializes a message object of type '<moveResult>"
  (cl:let* ((signed (cl:slot-value msg 'res_num)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveResult>) istream)
  "Deserializes a message object of type '<moveResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'res_num) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveResult>)))
  "Returns string type for a message object of type '<moveResult>"
  "actionlib_tut/moveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveResult)))
  "Returns string type for a message object of type 'moveResult"
  "actionlib_tut/moveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveResult>)))
  "Returns md5sum for a message object of type '<moveResult>"
  "00ad6002ee5b648cdbd85da44efc1911")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveResult)))
  "Returns md5sum for a message object of type 'moveResult"
  "00ad6002ee5b648cdbd85da44efc1911")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveResult>)))
  "Returns full string definition for message of type '<moveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 res_num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveResult)))
  "Returns full string definition for message of type 'moveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 res_num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'moveResult
    (cl:cons ':res_num (res_num msg))
))
