(cl:defpackage rotor_control-msg
  (:use )
  (:export
   "<QROTORMOVEACTION>"
   "QROTORMOVEACTION"
   "<QROTORMOVEACTIONFEEDBACK>"
   "QROTORMOVEACTIONFEEDBACK"
   "<QROTORMOVEACTIONGOAL>"
   "QROTORMOVEACTIONGOAL"
   "<QROTORMOVEACTIONRESULT>"
   "QROTORMOVEACTIONRESULT"
   "<QROTORMOVEFEEDBACK>"
   "QROTORMOVEFEEDBACK"
   "<QROTORMOVEGOAL>"
   "QROTORMOVEGOAL"
   "<QROTORMOVERESULT>"
   "QROTORMOVERESULT"
  ))

