; Auto-generated. Do not edit!


(cl:in-package rotor_control-msg)


;//! \htmlinclude qrotorMoveFeedback.msg.html

(cl:defclass <qrotorMoveFeedback> (roslisp-msg-protocol:ros-message)
  ((dest
    :reader dest
    :initarg :dest
    :type cl:string
    :initform ""))
)

(cl:defclass qrotorMoveFeedback (<qrotorMoveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <qrotorMoveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'qrotorMoveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rotor_control-msg:<qrotorMoveFeedback> is deprecated: use rotor_control-msg:qrotorMoveFeedback instead.")))

(cl:ensure-generic-function 'dest-val :lambda-list '(m))
(cl:defmethod dest-val ((m <qrotorMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rotor_control-msg:dest-val is deprecated.  Use rotor_control-msg:dest instead.")
  (dest m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <qrotorMoveFeedback>) ostream)
  "Serializes a message object of type '<qrotorMoveFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'dest))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'dest))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <qrotorMoveFeedback>) istream)
  "Deserializes a message object of type '<qrotorMoveFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'dest) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'dest) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<qrotorMoveFeedback>)))
  "Returns string type for a message object of type '<qrotorMoveFeedback>"
  "rotor_control/qrotorMoveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'qrotorMoveFeedback)))
  "Returns string type for a message object of type 'qrotorMoveFeedback"
  "rotor_control/qrotorMoveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<qrotorMoveFeedback>)))
  "Returns md5sum for a message object of type '<qrotorMoveFeedback>"
  "5b71877c96ea31e76c519018632328bc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'qrotorMoveFeedback)))
  "Returns md5sum for a message object of type 'qrotorMoveFeedback"
  "5b71877c96ea31e76c519018632328bc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<qrotorMoveFeedback>)))
  "Returns full string definition for message of type '<qrotorMoveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string dest~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'qrotorMoveFeedback)))
  "Returns full string definition for message of type 'qrotorMoveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string dest~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <qrotorMoveFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'dest))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <qrotorMoveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'qrotorMoveFeedback
    (cl:cons ':dest (dest msg))
))
