// Auto-generated. Do not edit!

// (in-package actionlib_tut.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class moveResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.res_num = null;
    }
    else {
      if (initObj.hasOwnProperty('res_num')) {
        this.res_num = initObj.res_num
      }
      else {
        this.res_num = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type moveResult
    // Serialize message field [res_num]
    bufferOffset = _serializer.int32(obj.res_num, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type moveResult
    let len;
    let data = new moveResult(null);
    // Deserialize message field [res_num]
    data.res_num = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_tut/moveResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '00ad6002ee5b648cdbd85da44efc1911';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    int32 res_num
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new moveResult(null);
    if (msg.res_num !== undefined) {
      resolved.res_num = msg.res_num;
    }
    else {
      resolved.res_num = 0
    }

    return resolved;
    }
};

module.exports = moveResult;
