// Auto-generated. Do not edit!

// (in-package actionlib_tut.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class moveFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.feedback_num = null;
    }
    else {
      if (initObj.hasOwnProperty('feedback_num')) {
        this.feedback_num = initObj.feedback_num
      }
      else {
        this.feedback_num = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type moveFeedback
    // Serialize message field [feedback_num]
    bufferOffset = _serializer.int32(obj.feedback_num, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type moveFeedback
    let len;
    let data = new moveFeedback(null);
    // Deserialize message field [feedback_num]
    data.feedback_num = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_tut/moveFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '0ef00485d510719cdd8130a85bb4b231';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int32 feedback_num
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new moveFeedback(null);
    if (msg.feedback_num !== undefined) {
      resolved.feedback_num = msg.feedback_num;
    }
    else {
      resolved.feedback_num = 0
    }

    return resolved;
    }
};

module.exports = moveFeedback;
