// Generated by gencpp from file rotor_control/qrotorMoveActionGoal.msg
// DO NOT EDIT!


#ifndef ROTOR_CONTROL_MESSAGE_QROTORMOVEACTIONGOAL_H
#define ROTOR_CONTROL_MESSAGE_QROTORMOVEACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <rotor_control/qrotorMoveGoal.h>

namespace rotor_control
{
template <class ContainerAllocator>
struct qrotorMoveActionGoal_
{
  typedef qrotorMoveActionGoal_<ContainerAllocator> Type;

  qrotorMoveActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  qrotorMoveActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::rotor_control::qrotorMoveGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct qrotorMoveActionGoal_

typedef ::rotor_control::qrotorMoveActionGoal_<std::allocator<void> > qrotorMoveActionGoal;

typedef boost::shared_ptr< ::rotor_control::qrotorMoveActionGoal > qrotorMoveActionGoalPtr;
typedef boost::shared_ptr< ::rotor_control::qrotorMoveActionGoal const> qrotorMoveActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rotor_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'HasHeader': True, 'IsMessage': True}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'rotor_control': ['/home/dvir/catkin_ws/devel/share/rotor_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "463315252da6cf7d32cce65c5c5501a4";
  }

  static const char* value(const ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x463315252da6cf7dULL;
  static const uint64_t static_value2 = 0x32cce65c5c5501a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rotor_control/qrotorMoveActionGoal";
  }

  static const char* value(const ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
qrotorMoveGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: rotor_control/qrotorMoveGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Goal definition\n\
string dest \n\
";
  }

  static const char* value(const ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct qrotorMoveActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rotor_control::qrotorMoveActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::rotor_control::qrotorMoveGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROTOR_CONTROL_MESSAGE_QROTORMOVEACTIONGOAL_H
