// Auto-generated. Do not edit!

// (in-package rotor_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class qrotorMoveGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.dest = null;
    }
    else {
      if (initObj.hasOwnProperty('dest')) {
        this.dest = initObj.dest
      }
      else {
        this.dest = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type qrotorMoveGoal
    // Serialize message field [dest]
    bufferOffset = _serializer.string(obj.dest, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type qrotorMoveGoal
    let len;
    let data = new qrotorMoveGoal(null);
    // Deserialize message field [dest]
    data.dest = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.dest.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rotor_control/qrotorMoveGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5b71877c96ea31e76c519018632328bc';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Goal definition
    string dest 
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new qrotorMoveGoal(null);
    if (msg.dest !== undefined) {
      resolved.dest = msg.dest;
    }
    else {
      resolved.dest = ''
    }

    return resolved;
    }
};

module.exports = qrotorMoveGoal;
