// Generated by gencpp from file actionlib_tut/moveGoal.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUT_MESSAGE_MOVEGOAL_H
#define ACTIONLIB_TUT_MESSAGE_MOVEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_tut
{
template <class ContainerAllocator>
struct moveGoal_
{
  typedef moveGoal_<ContainerAllocator> Type;

  moveGoal_()
    : goal_num(0)  {
    }
  moveGoal_(const ContainerAllocator& _alloc)
    : goal_num(0)  {
  (void)_alloc;
    }



   typedef int32_t _goal_num_type;
  _goal_num_type goal_num;





  typedef boost::shared_ptr< ::actionlib_tut::moveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tut::moveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct moveGoal_

typedef ::actionlib_tut::moveGoal_<std::allocator<void> > moveGoal;

typedef boost::shared_ptr< ::actionlib_tut::moveGoal > moveGoalPtr;
typedef boost::shared_ptr< ::actionlib_tut::moveGoal const> moveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_tut::moveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_tut::moveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actionlib_tut

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'actionlib_tut': ['/home/dvir/catkin_ws/devel/share/actionlib_tut/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tut::moveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tut::moveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tut::moveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tut::moveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tut::moveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tut::moveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tut::moveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99fc8ea054f24b75e22a1cacf948e8fe";
  }

  static const char* value(const ::actionlib_tut::moveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99fc8ea054f24b75ULL;
  static const uint64_t static_value2 = 0xe22a1cacf948e8feULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tut::moveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_tut/moveGoal";
  }

  static const char* value(const ::actionlib_tut::moveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tut::moveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Goal definition\n\
int32 goal_num \n\
";
  }

  static const char* value(const ::actionlib_tut::moveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_tut::moveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tut::moveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_tut::moveGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUT_MESSAGE_MOVEGOAL_H
