// Generated by gencpp from file actionlib_tut/moveResult.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUT_MESSAGE_MOVERESULT_H
#define ACTIONLIB_TUT_MESSAGE_MOVERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_tut
{
template <class ContainerAllocator>
struct moveResult_
{
  typedef moveResult_<ContainerAllocator> Type;

  moveResult_()
    : res_num(0)  {
    }
  moveResult_(const ContainerAllocator& _alloc)
    : res_num(0)  {
  (void)_alloc;
    }



   typedef int32_t _res_num_type;
  _res_num_type res_num;





  typedef boost::shared_ptr< ::actionlib_tut::moveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tut::moveResult_<ContainerAllocator> const> ConstPtr;

}; // struct moveResult_

typedef ::actionlib_tut::moveResult_<std::allocator<void> > moveResult;

typedef boost::shared_ptr< ::actionlib_tut::moveResult > moveResultPtr;
typedef boost::shared_ptr< ::actionlib_tut::moveResult const> moveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_tut::moveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_tut::moveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actionlib_tut

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'HasHeader': False, 'IsFixedSize': True, 'IsMessage': True}
// {'actionlib_tut': ['/home/dvir/catkin_ws/devel/share/actionlib_tut/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct HasHeader< ::actionlib_tut::moveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tut::moveResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tut::moveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tut::moveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tut::moveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tut::moveResult_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tut::moveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00ad6002ee5b648cdbd85da44efc1911";
  }

  static const char* value(const ::actionlib_tut::moveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00ad6002ee5b648cULL;
  static const uint64_t static_value2 = 0xdbd85da44efc1911ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tut::moveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_tut/moveResult";
  }

  static const char* value(const ::actionlib_tut::moveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tut::moveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 res_num\n\
";
  }

  static const char* value(const ::actionlib_tut::moveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_tut::moveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tut::moveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_tut::moveResult_<ContainerAllocator>& v)
  {
    s << indent << "res_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.res_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUT_MESSAGE_MOVERESULT_H
