// Generated by gencpp from file actionlib_tut/moveFeedback.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUT_MESSAGE_MOVEFEEDBACK_H
#define ACTIONLIB_TUT_MESSAGE_MOVEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_tut
{
template <class ContainerAllocator>
struct moveFeedback_
{
  typedef moveFeedback_<ContainerAllocator> Type;

  moveFeedback_()
    : feedback_num(0)  {
    }
  moveFeedback_(const ContainerAllocator& _alloc)
    : feedback_num(0)  {
  (void)_alloc;
    }



   typedef int32_t _feedback_num_type;
  _feedback_num_type feedback_num;





  typedef boost::shared_ptr< ::actionlib_tut::moveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tut::moveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct moveFeedback_

typedef ::actionlib_tut::moveFeedback_<std::allocator<void> > moveFeedback;

typedef boost::shared_ptr< ::actionlib_tut::moveFeedback > moveFeedbackPtr;
typedef boost::shared_ptr< ::actionlib_tut::moveFeedback const> moveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_tut::moveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_tut::moveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actionlib_tut

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'HasHeader': False, 'IsMessage': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_tut': ['/home/dvir/catkin_ws/devel/share/actionlib_tut/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tut::moveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tut::moveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tut::moveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tut::moveFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tut::moveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tut::moveFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tut::moveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ef00485d510719cdd8130a85bb4b231";
  }

  static const char* value(const ::actionlib_tut::moveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ef00485d510719cULL;
  static const uint64_t static_value2 = 0xdd8130a85bb4b231ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tut::moveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_tut/moveFeedback";
  }

  static const char* value(const ::actionlib_tut::moveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tut::moveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
int32 feedback_num\n\
\n\
";
  }

  static const char* value(const ::actionlib_tut::moveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_tut::moveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tut::moveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_tut::moveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.feedback_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUT_MESSAGE_MOVEFEEDBACK_H
